apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: signupsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: signupsvc
     labels:
       app: signupsvc
   spec:
     containers:
       - name: signupsvcluster
         image: "" 
         imagePullPolicy: Always
         env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
         ports:
         - containerPort: 3004
         livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: signupsvc
 labels:
   app: signupsvc
spec:
 type: NodePort
 selector:
   app: signupsvc
 ports:
  - protocol: TCP
    name: signupsvc
    port: 3004
    targetPort: 3004