apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: signupsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: signupsvc
     labels:
       app: signupsvc
   spec:
     containers:
       - name: signupsvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
         - containerPort: 3000
         livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: signupsvcname 
 labels:
   app: signupsvc
spec:
 type: NodePort
 selector:
   app: signupsvc
 ports:
  - protocol: TCP
    name: signupsvc
    port: 3000  
    targetPort: 3000 