apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: loginsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: loginsvc
     labels:
       app: loginsvc
   spec:
     containers:
       - name: loginsvcluster
         image: "" 
         imagePullPolicy: Always
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-login
                key: NODE_ENV
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: env-login
                key: DATABASE
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: env-login
                key: PORT
          - name: HOSTNAME
            valueFrom:
              secretKeyRef:
                name: env-login
                key: HOSTNAME
          - name: PROTOCOL
            valueFrom:
              secretKeyRef:
                name: env-login
                key: PROTOCOL
         ports:
         - containerPort: 3003
         livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: loginsvc
 labels:
   app: loginsvc
spec:
 type: NodePort
 selector:
   app: loginsvc
 ports:
  - protocol: TCP
    name: loginsvc
    port: 3003  
    targetPort: 3003