apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: loginsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: loginsvc
     labels:
       app: loginsvc
   spec:
     containers:
       - name: loginsvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
         - containerPort: 3001
         livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: loginsvcname 
 labels:
   app: loginsvc
spec:
 type: NodePort
 selector:
   app: loginsvc
 ports:
  - protocol: TCP
    name: loginsvc
    port: 3001  
    nodePort: 30093