apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: bookingsvc
     labels:
       app: bookingsvc
   spec:
     containers:
       - name: bookscvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
         - containerPort: 3000
         livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: bookingsvcname 
 labels:
   app: bookingsvc
spec:
 type: NodePort
 selector:
   app: bookingsvc
 ports:
  - protocol: TCP
    name: bookingsvc
    port: 3000
    targetPort: 3000  