apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: checkinsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: checkinsvc
     labels:
       app: checkinsvc
   spec:
     containers:
       - name: checkinsvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
         - containerPort: 3004
         livenessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: checkinsvcname 
 labels:
   app: checkinsvc
spec:
 type: NodePort
 selector:
   app: checkinsvc
 ports:
  - protocol: TCP
    name: checkinsvc
    port: 3004  
    nodePort: 30091