apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
 name: checkinsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: checkinsvc
     labels:
       app: checkinsvc
   spec:
     containers:
       - name: checkinsvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
          containerPort: 5000
          name: db2
         volumeMounts:
          - name: db2-storage
            mounPath: /home/db2inst1/db2inst1
         livenessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
 volumeClaimTemplates:
  - metadata:
      name: zookeeper-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: rbd 
---
apiVersion: v1
kind: Service
metadata:
 name: checkinsvcname 
 labels:
   app: checkinsvc
spec:
 type: NodePort
 selector:
   app: checkinsvc
 ports:
  - protocol: TCP
    name: checkinsvc
    port: 5000  
    nodePort: 30096
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db2-pv-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi