apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
 name: db2svc 
spec:
 replicas: 1
 template:
   metadata:
     name: db2svc
     labels:
       app: db2svc
   spec:
     containers:
       - name: db2svcluster
         image: "" 
         imagePullPolicy: Never
         ports:
          containerPort: 5000
          name: db2
         volumeMounts:
          - name: db2-storage
            mounPath: /home/db2inst1/db2inst1
         livenessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 30
 volumeClaimTemplates:
  - metadata:
      name: db2-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: rbd 
---
apiVersion: v1
kind: Service
metadata:
 name: db2svcname 
 labels:
   app: db2svc
spec:
 type: NodePort
 selector:
   app: db2svc
 ports:
  - protocol: TCP
    name: db2svc
    port: 5000  
    targetPort: 5000
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db2-pv-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi