apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: db2svc 
spec:
 replicas: 1
 template:
   metadata:
     name: db2svc
     labels:
       app: db2svc
   spec:
     containers:
       - name: db2svcluster
         image: "ibmcom/db2express-c"
         command: ["/bin/sh"]
         args: ["-c", "/home/db2inst1/sqllib/adm/db2start;while true; do echo hello; sleep 10;done"]
         imagePullPolicy: Always
         env:
            - name: DB2INST1_PASSWORD
              value: db2inst1-pwd
            - name: LICENSE
              value: accept
         ports:
         - containerPort: 50000
        #  livenessProbe:
        #     httpGet:
        #       path: /
        #       port: 3008
        #     initialDelaySeconds: 30
        #     periodSeconds: 30
        #  readinessProbe:
        #     httpGet:
        #       path: /
        #       port: 3008
        #     initialDelaySeconds: 30
        #     periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: db2svcname 
 labels:
   app: db2svc
spec:
 type: NodePort
 selector:
   app: db2svc
 ports:
  - protocol: TCP
    name: db2svc
    port: 50000  
    nodePort: 30098