apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: listingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: listingsvc
     labels:
       app: listingsvc
   spec:
     containers:
       - name: listingsvcluster
         image: "" 
         imagePullPolicy: Always
         ports:
         - containerPort: 3000
         livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: listingsvcname 
 labels:
   app: listingsvc
spec:
 type: NodePort
 selector:
   app: listingsvc
 ports:
  - protocol: TCP
    name: listingsvc
    port: 3000  
    targetPort: 3000 
