apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: listingsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: listingsvc
     labels:
       app: listingsvc
   spec:
     containers:
       - name: listingsvcluster
         image: "" 
         imagePullPolicy: Always
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
         ports:
         - containerPort: 3002
         livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: listingsvc
 labels:
   app: listingsvc
spec:
 type: NodePort
 selector:
   app: listingsvc
 ports:
  - protocol: TCP
    name: listingsvc
    port: 3002  
    targetPort: 3002 
