apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: listingsvc 
spec:
 replicas: 1
 template:
   metadata:
     name: listingsvc
     labels:
       app: listingsvc
   spec:
     containers:
       - name: listingsvcluster
         image: "" 
         imagePullPolicy: Never
         ports:
         - containerPort: 3002
         livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: listingsvcname 
 labels:
   app: listingsvc
spec:
 type: NodePort
 selector:
   app: listingsvc
 ports:
  - protocol: TCP
    name: listingsvc
    port: 3002  
    nodePort: 30092