apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: icp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: icp.example.com
    http:
      paths:
      - path: /signupsvc
        backend:
          serviceName: signupsvc
          servicePort: 3004