apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: icp
spec:
  rules:
  - host: icp.example.com
    http: 
      paths:
      - path: /bookingsvc
        backend:
          serviceName: bookingsvc
          servicePort: 3000
      - path: /checkinsvc
        backend:
          serviceName: checkinsvc
          servicePort: 3001
      - path: /listingsvc
        backend:
          serviceName: listingsvc
          servicePort: 3002
      - path: /loginsvc
        backend:
          serviceName: loginsvc
          servicePort: 3003
      - path: /signupsvc
        backend:
          serviceName: signupsvc
          servicePort: 3004