apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: checkinsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: checkinsvc
     labels:
       app: checkinsvc
   spec:
     containers:
       - name: checkinsvcluster
         image: "" 
         imagePullPolicy: Always
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
         ports:
         - containerPort: 3001
         livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: checkinsvc
 labels:
   app: checkinsvc
spec:
 type: NodePort
 selector:
   app: checkinsvc
 ports:
  - protocol: TCP
    name: checkinsvc
    port: 3001
    targetPort: 3001   
