apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: checkinsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: checkinsvc
     labels:
       app: checkinsvc
   spec:
     containers:
       - name: checkinsvcluster
         image: "" 
         imagePullPolicy: Always
         ports:
         - containerPort: 3000
         livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
         readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          
---
apiVersion: v1
kind: Service
metadata:
 name: checkinsvc
 labels:
   app: checkinsvc
spec:
 type: NodePort
 selector:
   app: checkinsvc
 ports:
  - protocol: TCP
    name: checkinsvc
    port: 3000
    targetPort: 3000   
